apiVersion: v1
kind: Secret
metadata:
  name: etos-api-token
  annotations:
    kubernetes.io/service-account.name: etos-api
  labels:
    app.kubernetes.io/name: etos-api
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: api
type: kubernetes.io/service-account-token
